import type { AggregatedBundle } from '../types.js';

export function generateClaudeMdContent(
  bundle: AggregatedBundle,
  projectName: string,
  version: string,
  compiledAt: string,
  totalFacts: number,
): string {
  const openCount = bundle.openQuestions?.filter(q => q.status === 'open').length ?? 0;
  const criticalInstructions = (bundle.agentInstructions ?? [])
    .filter(a => a.priority === 'critical')
    .slice(0, 5);

  const lines: string[] = [
    `# ${projectName}`,
    '',
    `> SpecFlow AI context snapshot — ${version} (${compiledAt.split('T')[0]})`,
    `> ${totalFacts} facts extracted · ${openCount} open questions`,
    '',
    '## Project at a Glance',
    '',
    `**Stage:** ${bundle.overview.stage}  `,
    `**Goal:** ${bundle.overview.description}`,
    '',
    '---',
    '',
    '## Context Map (read in order)',
    '',
    '| # | File | What You\'ll Find |',
    '|---|------|-------------------|',
    '| 0 | [Overview](docs/spec-flow/00_overview.md) | Goals, stakeholders, stage |',
    '| 1 | [Product Spec](docs/spec-flow/01_product_spec.md) | Users, features, scope |',
    '| 2 | [User Flows](docs/spec-flow/02_user_flows.md) | Actor actions, edge cases |',
    '| 3 | [Tech Constraints](docs/spec-flow/03_technical_constraints.md) | Boundaries, rationale |',
    '| 4 | [Data Model](docs/spec-flow/04_data_model.md) | Entities, fields, relationships |',
    '| 5 | [Tasks](docs/spec-flow/05_task_breakdown.md) | Prioritized work items |',
    '| 6 | [Agent Instructions](docs/spec-flow/06_agent_instructions.md) | Critical rules for AI agents |',
    '| 7 | [Open Questions](docs/spec-flow/07_open_questions.md) | Unresolved decisions |',
    '| 8 | [Decision Log](docs/spec-flow/08_decision_log.md) | Past decisions + rationale |',
    '| 9 | [Codebase Analysis](docs/spec-flow/09_codebase_analysis.md) | Source scan results |',
    '| 10 | [Tech Stack](docs/spec-flow/10_tech_stack.md) | Technologies + versions |',
    '| 11 | [Architecture](docs/spec-flow/11_architecture.md) | Components, data flow, deploy |',
    '',
    '---',
    '',
    '## Standing Orders',
    '',
  ];

  if (criticalInstructions.length > 0) {
    for (const inst of criticalInstructions) {
      lines.push(`- ${inst.content}`);
    }
  } else {
    lines.push('- Always check `07_open_questions.md` before making assumptions');
    lines.push('- Follow task priorities in `05_task_breakdown.md`');
    lines.push('- Respect constraints listed in `03_technical_constraints.md`');
    lines.push('- Reference `08_decision_log.md` before reversing past decisions');
  }

  lines.push('');
  lines.push('---');
  lines.push('');

  if (openCount > 0) {
    lines.push(`## Open Questions (${openCount})`);
    lines.push('');
    const firstQuestions = bundle.openQuestions!
      .filter(q => q.status === 'open')
      .slice(0, 3);
    for (const q of firstQuestions) {
      lines.push(`- [ ] ${q.question}`);
    }
    if (openCount > 3) {
      lines.push(`- ... and ${openCount - 3} more → [Open Questions](docs/spec-flow/07_open_questions.md)`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by SpecFlow AI · Version ${version}*`);

  return lines.join('\n');
}
